### ISSUE TITLE
Invalid pip module name for the verifier

### ISSUE THREAD

**Issue by arnaud-m** [PACE-challenge/pacechallenge.org#14]
Hi,

It may save 5 minutes to other people to fix the module name to [pace2024-verifier](https://pypi.org/project/pace2024-verifier/). 
https://github.com/PACE-challenge/pacechallenge.org/blob/b8b8d64d0f25c49b55dea62ed9d3c0d307fe68e1/2024/verifier.md?plain=1#L13

Thank you for the challenge.

**Comment by PhKindermann** [comment]
Thank you for the note, I fixed it!
