### ISSUE TITLE
Cannot import name 'read_graph' in the visualizer

### ISSUE THREAD

**Issue by arnaud-m** [PACE-challenge/pacechallenge.org#15]
Hello,

I cannot use the visualizer because the read_graph function is not found in the module `utils`.

https://github.com/PACE-challenge/pacechallenge.org/blob/c1c5270257f1eb6cd542bda42e53c8c4e5de2acc/2024/visualizer.py#L4

Here is below the description of the installed modules `utils` on  Fedora 38.
```
Name: utils
Version: 1.0.1
Summary: A grab-bag of utility functions and objects
Home-page: http://github.com/haaksmash/pyutils
Author: Haak Saxberg
Author-email: haak.erling@gmail.com
License: UNKNOWN
Location: /home/nono/.local/lib/python3.11/site-packages
Requires: 
Required-by: 

Name: python3-utils
Version: 0.4.0
Summary: Useful collection of python3 utilities
Home-page: https://github.com/micahhausler/python3-utils
Author: Micah Hausler
Author-email: hausler.m@gmail.com
License: MIT
Location: /home/nono/.local/lib/python3.11/site-packages
Requires: six
Required-by: 
```
I noticed that a `read_graph` function is available in the verifier, but failed to import it.
```python3
from pace2024_verifier import read_graph
```

I am not a python expert and I did not find any other relevant `utils` package.
Thank you for your help.

**Comment by PhKindermann** [comment]
Thank you Arnaud for the note! We have written our only `utils.py`, which is not public. We added all the functions we use from our `utils.py` directly into the visualizer. We bundled the visualizer with a `requirements.txt` to install the required packages.
